import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { ProviderNextUI } from "@/providers/ProviderNextUI";
import { ClerkProvider } from "@clerk/nextjs";

import { FavoriteProvider } from "@/contexts/FavoriteContext";
import { CartProvider } from "@/contexts/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider
          appearance={{
            elements: {
              formButtonPrimary: "primary-gradient",
              footerActionLink: "primary-text-gradient hover:text-primary-500",
            },
          }}
        >
          <FavoriteProvider>
            <CartProvider>
              <ProviderNextUI>
                <ToastContainer autoClose={2000} />
                {children}
              </ProviderNextUI>
            </CartProvider>
          </FavoriteProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
